// Code generated by entc, DO NOT EDIT.

package personalaccesstoken

import (
	"time"
)

const (
	// Label holds the string label denoting the personalaccesstoken type in the database.
	Label = "personal_access_token"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldToken holds the string denoting the token field in the database.
	FieldToken = "token"
	// FieldAbilities holds the string denoting the abilities field in the database.
	FieldAbilities = "abilities"
	// FieldExpirationAt holds the string denoting the expiration_at field in the database.
	FieldExpirationAt = "expiration_at"
	// FieldLastUsedAt holds the string denoting the last_used_at field in the database.
	FieldLastUsedAt = "last_used_at"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// EdgeUser holds the string denoting the user edge name in mutations.
	EdgeUser = "user"
	// Table holds the table name of the personalaccesstoken in the database.
	Table = "personal_access_tokens"
	// UserTable is the table that holds the user relation/edge.
	UserTable = "personal_access_tokens"
	// UserInverseTable is the table name for the User entity.
	// It exists in this package in order to avoid circular dependency with the "user" package.
	UserInverseTable = "users"
	// UserColumn is the table column denoting the user relation/edge.
	UserColumn = "user_personal_access_tokens"
)

// Columns holds all SQL columns for personalaccesstoken fields.
var Columns = []string{
	FieldID,
	FieldName,
	FieldToken,
	FieldAbilities,
	FieldExpirationAt,
	FieldLastUsedAt,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the "personal_access_tokens"
// table and are not defined as standalone fields in the schema.
var ForeignKeys = []string{
	"user_personal_access_tokens",
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	for i := range ForeignKeys {
		if column == ForeignKeys[i] {
			return true
		}
	}
	return false
}

var (
	// TokenValidator is a validator for the "token" field. It is called by the builders before save.
	TokenValidator func(string) error
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
)
