// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/hsndmr/go-sanctum/ent/personalaccesstoken"
	"github.com/hsndmr/go-sanctum/ent/predicate"
)

// PersonalAccessTokenDelete is the builder for deleting a PersonalAccessToken entity.
type PersonalAccessTokenDelete struct {
	config
	hooks    []Hook
	mutation *PersonalAccessTokenMutation
}

// Where appends a list predicates to the PersonalAccessTokenDelete builder.
func (patd *PersonalAccessTokenDelete) Where(ps ...predicate.PersonalAccessToken) *PersonalAccessTokenDelete {
	patd.mutation.Where(ps...)
	return patd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (patd *PersonalAccessTokenDelete) Exec(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(patd.hooks) == 0 {
		affected, err = patd.sqlExec(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*PersonalAccessTokenMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			patd.mutation = mutation
			affected, err = patd.sqlExec(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(patd.hooks) - 1; i >= 0; i-- {
			if patd.hooks[i] == nil {
				return 0, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = patd.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, patd.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// ExecX is like Exec, but panics if an error occurs.
func (patd *PersonalAccessTokenDelete) ExecX(ctx context.Context) int {
	n, err := patd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (patd *PersonalAccessTokenDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := &sqlgraph.DeleteSpec{
		Node: &sqlgraph.NodeSpec{
			Table: personalaccesstoken.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: personalaccesstoken.FieldID,
			},
		},
	}
	if ps := patd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return sqlgraph.DeleteNodes(ctx, patd.driver, _spec)
}

// PersonalAccessTokenDeleteOne is the builder for deleting a single PersonalAccessToken entity.
type PersonalAccessTokenDeleteOne struct {
	patd *PersonalAccessTokenDelete
}

// Exec executes the deletion query.
func (patdo *PersonalAccessTokenDeleteOne) Exec(ctx context.Context) error {
	n, err := patdo.patd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{personalaccesstoken.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (patdo *PersonalAccessTokenDeleteOne) ExecX(ctx context.Context) {
	patdo.patd.ExecX(ctx)
}
