// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/hsndmr/go-sanctum/ent/personalaccesstoken"
	"github.com/hsndmr/go-sanctum/ent/predicate"
	"github.com/hsndmr/go-sanctum/ent/user"
)

// PersonalAccessTokenUpdate is the builder for updating PersonalAccessToken entities.
type PersonalAccessTokenUpdate struct {
	config
	hooks    []Hook
	mutation *PersonalAccessTokenMutation
}

// Where appends a list predicates to the PersonalAccessTokenUpdate builder.
func (patu *PersonalAccessTokenUpdate) Where(ps ...predicate.PersonalAccessToken) *PersonalAccessTokenUpdate {
	patu.mutation.Where(ps...)
	return patu
}

// SetName sets the "name" field.
func (patu *PersonalAccessTokenUpdate) SetName(s string) *PersonalAccessTokenUpdate {
	patu.mutation.SetName(s)
	return patu
}

// SetUserID sets the "user_id" field.
func (patu *PersonalAccessTokenUpdate) SetUserID(i int) *PersonalAccessTokenUpdate {
	patu.mutation.SetUserID(i)
	return patu
}

// SetToken sets the "token" field.
func (patu *PersonalAccessTokenUpdate) SetToken(s string) *PersonalAccessTokenUpdate {
	patu.mutation.SetToken(s)
	return patu
}

// SetAbilities sets the "abilities" field.
func (patu *PersonalAccessTokenUpdate) SetAbilities(s []string) *PersonalAccessTokenUpdate {
	patu.mutation.SetAbilities(s)
	return patu
}

// ClearAbilities clears the value of the "abilities" field.
func (patu *PersonalAccessTokenUpdate) ClearAbilities() *PersonalAccessTokenUpdate {
	patu.mutation.ClearAbilities()
	return patu
}

// SetExpirationAt sets the "expiration_at" field.
func (patu *PersonalAccessTokenUpdate) SetExpirationAt(t time.Time) *PersonalAccessTokenUpdate {
	patu.mutation.SetExpirationAt(t)
	return patu
}

// SetLastUsedAt sets the "last_used_at" field.
func (patu *PersonalAccessTokenUpdate) SetLastUsedAt(t time.Time) *PersonalAccessTokenUpdate {
	patu.mutation.SetLastUsedAt(t)
	return patu
}

// SetNillableLastUsedAt sets the "last_used_at" field if the given value is not nil.
func (patu *PersonalAccessTokenUpdate) SetNillableLastUsedAt(t *time.Time) *PersonalAccessTokenUpdate {
	if t != nil {
		patu.SetLastUsedAt(*t)
	}
	return patu
}

// ClearLastUsedAt clears the value of the "last_used_at" field.
func (patu *PersonalAccessTokenUpdate) ClearLastUsedAt() *PersonalAccessTokenUpdate {
	patu.mutation.ClearLastUsedAt()
	return patu
}

// SetUpdatedAt sets the "updated_at" field.
func (patu *PersonalAccessTokenUpdate) SetUpdatedAt(t time.Time) *PersonalAccessTokenUpdate {
	patu.mutation.SetUpdatedAt(t)
	return patu
}

// SetUser sets the "user" edge to the User entity.
func (patu *PersonalAccessTokenUpdate) SetUser(u *User) *PersonalAccessTokenUpdate {
	return patu.SetUserID(u.ID)
}

// Mutation returns the PersonalAccessTokenMutation object of the builder.
func (patu *PersonalAccessTokenUpdate) Mutation() *PersonalAccessTokenMutation {
	return patu.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (patu *PersonalAccessTokenUpdate) ClearUser() *PersonalAccessTokenUpdate {
	patu.mutation.ClearUser()
	return patu
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (patu *PersonalAccessTokenUpdate) Save(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	patu.defaults()
	if len(patu.hooks) == 0 {
		if err = patu.check(); err != nil {
			return 0, err
		}
		affected, err = patu.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*PersonalAccessTokenMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			if err = patu.check(); err != nil {
				return 0, err
			}
			patu.mutation = mutation
			affected, err = patu.sqlSave(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(patu.hooks) - 1; i >= 0; i-- {
			if patu.hooks[i] == nil {
				return 0, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = patu.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, patu.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// SaveX is like Save, but panics if an error occurs.
func (patu *PersonalAccessTokenUpdate) SaveX(ctx context.Context) int {
	affected, err := patu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (patu *PersonalAccessTokenUpdate) Exec(ctx context.Context) error {
	_, err := patu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (patu *PersonalAccessTokenUpdate) ExecX(ctx context.Context) {
	if err := patu.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (patu *PersonalAccessTokenUpdate) defaults() {
	if _, ok := patu.mutation.UpdatedAt(); !ok {
		v := personalaccesstoken.UpdateDefaultUpdatedAt()
		patu.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (patu *PersonalAccessTokenUpdate) check() error {
	if v, ok := patu.mutation.Token(); ok {
		if err := personalaccesstoken.TokenValidator(v); err != nil {
			return &ValidationError{Name: "token", err: fmt.Errorf(`ent: validator failed for field "PersonalAccessToken.token": %w`, err)}
		}
	}
	if _, ok := patu.mutation.UserID(); patu.mutation.UserCleared() && !ok {
		return errors.New(`ent: clearing a required unique edge "PersonalAccessToken.user"`)
	}
	return nil
}

func (patu *PersonalAccessTokenUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   personalaccesstoken.Table,
			Columns: personalaccesstoken.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: personalaccesstoken.FieldID,
			},
		},
	}
	if ps := patu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := patu.mutation.Name(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: personalaccesstoken.FieldName,
		})
	}
	if value, ok := patu.mutation.Token(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: personalaccesstoken.FieldToken,
		})
	}
	if value, ok := patu.mutation.Abilities(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeJSON,
			Value:  value,
			Column: personalaccesstoken.FieldAbilities,
		})
	}
	if patu.mutation.AbilitiesCleared() {
		_spec.Fields.Clear = append(_spec.Fields.Clear, &sqlgraph.FieldSpec{
			Type:   field.TypeJSON,
			Column: personalaccesstoken.FieldAbilities,
		})
	}
	if value, ok := patu.mutation.ExpirationAt(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: personalaccesstoken.FieldExpirationAt,
		})
	}
	if value, ok := patu.mutation.LastUsedAt(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: personalaccesstoken.FieldLastUsedAt,
		})
	}
	if patu.mutation.LastUsedAtCleared() {
		_spec.Fields.Clear = append(_spec.Fields.Clear, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Column: personalaccesstoken.FieldLastUsedAt,
		})
	}
	if value, ok := patu.mutation.UpdatedAt(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: personalaccesstoken.FieldUpdatedAt,
		})
	}
	if patu.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   personalaccesstoken.UserTable,
			Columns: []string{personalaccesstoken.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: user.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := patu.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   personalaccesstoken.UserTable,
			Columns: []string{personalaccesstoken.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: user.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, patu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{personalaccesstoken.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{err.Error(), err}
		}
		return 0, err
	}
	return n, nil
}

// PersonalAccessTokenUpdateOne is the builder for updating a single PersonalAccessToken entity.
type PersonalAccessTokenUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *PersonalAccessTokenMutation
}

// SetName sets the "name" field.
func (patuo *PersonalAccessTokenUpdateOne) SetName(s string) *PersonalAccessTokenUpdateOne {
	patuo.mutation.SetName(s)
	return patuo
}

// SetUserID sets the "user_id" field.
func (patuo *PersonalAccessTokenUpdateOne) SetUserID(i int) *PersonalAccessTokenUpdateOne {
	patuo.mutation.SetUserID(i)
	return patuo
}

// SetToken sets the "token" field.
func (patuo *PersonalAccessTokenUpdateOne) SetToken(s string) *PersonalAccessTokenUpdateOne {
	patuo.mutation.SetToken(s)
	return patuo
}

// SetAbilities sets the "abilities" field.
func (patuo *PersonalAccessTokenUpdateOne) SetAbilities(s []string) *PersonalAccessTokenUpdateOne {
	patuo.mutation.SetAbilities(s)
	return patuo
}

// ClearAbilities clears the value of the "abilities" field.
func (patuo *PersonalAccessTokenUpdateOne) ClearAbilities() *PersonalAccessTokenUpdateOne {
	patuo.mutation.ClearAbilities()
	return patuo
}

// SetExpirationAt sets the "expiration_at" field.
func (patuo *PersonalAccessTokenUpdateOne) SetExpirationAt(t time.Time) *PersonalAccessTokenUpdateOne {
	patuo.mutation.SetExpirationAt(t)
	return patuo
}

// SetLastUsedAt sets the "last_used_at" field.
func (patuo *PersonalAccessTokenUpdateOne) SetLastUsedAt(t time.Time) *PersonalAccessTokenUpdateOne {
	patuo.mutation.SetLastUsedAt(t)
	return patuo
}

// SetNillableLastUsedAt sets the "last_used_at" field if the given value is not nil.
func (patuo *PersonalAccessTokenUpdateOne) SetNillableLastUsedAt(t *time.Time) *PersonalAccessTokenUpdateOne {
	if t != nil {
		patuo.SetLastUsedAt(*t)
	}
	return patuo
}

// ClearLastUsedAt clears the value of the "last_used_at" field.
func (patuo *PersonalAccessTokenUpdateOne) ClearLastUsedAt() *PersonalAccessTokenUpdateOne {
	patuo.mutation.ClearLastUsedAt()
	return patuo
}

// SetUpdatedAt sets the "updated_at" field.
func (patuo *PersonalAccessTokenUpdateOne) SetUpdatedAt(t time.Time) *PersonalAccessTokenUpdateOne {
	patuo.mutation.SetUpdatedAt(t)
	return patuo
}

// SetUser sets the "user" edge to the User entity.
func (patuo *PersonalAccessTokenUpdateOne) SetUser(u *User) *PersonalAccessTokenUpdateOne {
	return patuo.SetUserID(u.ID)
}

// Mutation returns the PersonalAccessTokenMutation object of the builder.
func (patuo *PersonalAccessTokenUpdateOne) Mutation() *PersonalAccessTokenMutation {
	return patuo.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (patuo *PersonalAccessTokenUpdateOne) ClearUser() *PersonalAccessTokenUpdateOne {
	patuo.mutation.ClearUser()
	return patuo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (patuo *PersonalAccessTokenUpdateOne) Select(field string, fields ...string) *PersonalAccessTokenUpdateOne {
	patuo.fields = append([]string{field}, fields...)
	return patuo
}

// Save executes the query and returns the updated PersonalAccessToken entity.
func (patuo *PersonalAccessTokenUpdateOne) Save(ctx context.Context) (*PersonalAccessToken, error) {
	var (
		err  error
		node *PersonalAccessToken
	)
	patuo.defaults()
	if len(patuo.hooks) == 0 {
		if err = patuo.check(); err != nil {
			return nil, err
		}
		node, err = patuo.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*PersonalAccessTokenMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			if err = patuo.check(); err != nil {
				return nil, err
			}
			patuo.mutation = mutation
			node, err = patuo.sqlSave(ctx)
			mutation.done = true
			return node, err
		})
		for i := len(patuo.hooks) - 1; i >= 0; i-- {
			if patuo.hooks[i] == nil {
				return nil, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = patuo.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, patuo.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX is like Save, but panics if an error occurs.
func (patuo *PersonalAccessTokenUpdateOne) SaveX(ctx context.Context) *PersonalAccessToken {
	node, err := patuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (patuo *PersonalAccessTokenUpdateOne) Exec(ctx context.Context) error {
	_, err := patuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (patuo *PersonalAccessTokenUpdateOne) ExecX(ctx context.Context) {
	if err := patuo.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (patuo *PersonalAccessTokenUpdateOne) defaults() {
	if _, ok := patuo.mutation.UpdatedAt(); !ok {
		v := personalaccesstoken.UpdateDefaultUpdatedAt()
		patuo.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (patuo *PersonalAccessTokenUpdateOne) check() error {
	if v, ok := patuo.mutation.Token(); ok {
		if err := personalaccesstoken.TokenValidator(v); err != nil {
			return &ValidationError{Name: "token", err: fmt.Errorf(`ent: validator failed for field "PersonalAccessToken.token": %w`, err)}
		}
	}
	if _, ok := patuo.mutation.UserID(); patuo.mutation.UserCleared() && !ok {
		return errors.New(`ent: clearing a required unique edge "PersonalAccessToken.user"`)
	}
	return nil
}

func (patuo *PersonalAccessTokenUpdateOne) sqlSave(ctx context.Context) (_node *PersonalAccessToken, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   personalaccesstoken.Table,
			Columns: personalaccesstoken.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: personalaccesstoken.FieldID,
			},
		},
	}
	id, ok := patuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "PersonalAccessToken.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := patuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, personalaccesstoken.FieldID)
		for _, f := range fields {
			if !personalaccesstoken.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != personalaccesstoken.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := patuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := patuo.mutation.Name(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: personalaccesstoken.FieldName,
		})
	}
	if value, ok := patuo.mutation.Token(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: personalaccesstoken.FieldToken,
		})
	}
	if value, ok := patuo.mutation.Abilities(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeJSON,
			Value:  value,
			Column: personalaccesstoken.FieldAbilities,
		})
	}
	if patuo.mutation.AbilitiesCleared() {
		_spec.Fields.Clear = append(_spec.Fields.Clear, &sqlgraph.FieldSpec{
			Type:   field.TypeJSON,
			Column: personalaccesstoken.FieldAbilities,
		})
	}
	if value, ok := patuo.mutation.ExpirationAt(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: personalaccesstoken.FieldExpirationAt,
		})
	}
	if value, ok := patuo.mutation.LastUsedAt(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: personalaccesstoken.FieldLastUsedAt,
		})
	}
	if patuo.mutation.LastUsedAtCleared() {
		_spec.Fields.Clear = append(_spec.Fields.Clear, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Column: personalaccesstoken.FieldLastUsedAt,
		})
	}
	if value, ok := patuo.mutation.UpdatedAt(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: personalaccesstoken.FieldUpdatedAt,
		})
	}
	if patuo.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   personalaccesstoken.UserTable,
			Columns: []string{personalaccesstoken.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: user.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := patuo.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   personalaccesstoken.UserTable,
			Columns: []string{personalaccesstoken.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: user.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &PersonalAccessToken{config: patuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, patuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{personalaccesstoken.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{err.Error(), err}
		}
		return nil, err
	}
	return _node, nil
}
