// Code generated by entc, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// PersonalAccessToken is the predicate function for personalaccesstoken builders.
type PersonalAccessToken func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
